### PR TITLE
design-pages: added Get and Set per-Component Debug-Level

### PR DESCRIPTION
**Pull request by aplopez**
This Design Page is related to https://github.com/SSSD/sssd/issues/6019

### CODE REVIEW

**Comment by alexey-tikhonov** [comment]
@aplopez, very detailed write-up :+1: 

@pbrezina, didn't you recently mention that `sssctl` ought to be re-implemented in python (and hence any large modification of C-based version are undesirable)?

This especially applies to messing with config files. Code to make those manipulations atomic in C won't be neat...

**Comment by pbrezina** [comment]
> @aplopez, very detailed write-up +1
> 
> @pbrezina, didn't you recently mention that `sssctl` ought to be re-implemented in python (and hence any large modification of C-based version is undesirable)?

Yes, `get` operation is not difficult and it is a nice first task for Alejandro.

> This especially applies to messing with config files. Code to make those manipulations atomic in C won't be neat...

Setting the debug level permanently is something we added on top of the original request. I'm not yet familiar with libini write api, If it will be more difficult, we can drop it.

**Comment by aplopez** [comment]
> Setting the debug level permanently is something we added on top of the original request. I'm not yet familiar with libini write api, If it will be more difficult, we can drop it.

Reading and setting the debug level is done using `confdb`, but to make it persistent `libini` must be used in parallel. This seems to me a bit awkward, specially because (if I understood correctly) we need to initialize the library and structures, read the configuration, modify it and write the whole file again, hoping nobody else is doing the same thing at the same time (race condition - I don't know if `libini` locks the file but it would be most unusual).

If the tool will be re-implemented in the near future, I think we can skip the feature.

**Comment by pbrezina** [comment]
Ok, I agree.

**Comment by aplopez** [comment]
Shall I remove the paragraph talking about the --persistent flag?

**Comment by pbrezina** [comment]
Yes, please. Also update it to the latest version (switch to dbus instead of reading confdb).

**Comment by pbrezina** [comment]
Thank you. It looks good, but lets push this after the PR is accepted so further changes can be incorporated if needed.

**Comment by aplopez** [comment]
Updated the design page to reflect the latest implementation.

**Review by pbrezina — APPROVED** [review]

**Pull request merged**
